#Use the current Node Image
FROM node:current-alpine3.21

#Set the working directory
WORKDIR /app/frontend

#Copy package-lock.json and package.json into the working directory then install node modules
COPY package*.json ./
RUN npm install

#Copy the rest
COPY . .

#Expose port 5173 inside the container
EXPOSE 5173

#Start the server
CMD ["npm", "run", "dev"]