#Get a python 3.13 image 
FROM python:3.13-slim

#Set the working directory
WORKDIR /app/backend

#Copy requirements.txt into the working directory and install the neseccary packages using pip
COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

#Copy the rest
COPY ./api ./api

#Expose port 8000 inside the container
EXPOSE 8000

#Start the server
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]